# Generated by Django 4.2.5 on 2023-09-05 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('about', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='bodybuilding.muscle')),
                ('parentId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='bodybuilding.muscle')),
            ],
        ),
    ]
