# Generated by Django 4.2.5 on 2023-09-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodybuilding', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='childId',
            new_name='child',
        ),
        migrations.RenameField(
            model_name='relation',
            old_name='parentId',
            new_name='parent',
        ),
    ]
