# Generated by Django 4.2.5 on 2023-09-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodybuilding', '0002_rename_childid_relation_child_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('about', models.TextField(blank=True, verbose_name='Описание')),
                ('muscles', models.ManyToManyField(to='bodybuilding.muscle')),
            ],
        ),
    ]
