# Generated by Django 4.2.5 on 2023-10-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodybuilding', '0003_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='muscles',
        ),
        migrations.AddField(
            model_name='muscle',
            name='exercises',
            field=models.ManyToManyField(to='bodybuilding.exercise'),
        ),
    ]
