# Generated by Django 4.2.5 on 2023-10-04 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodybuilding', '0004_remove_exercise_muscles_muscle_exercises'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Цель')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('cooking', models.TextField(blank=True, verbose_name='Приготовление')),
                ('ingredients', models.TextField(blank=True, verbose_name='Ингридиенты')),
                ('nutrients', models.CharField(max_length=50, verbose_name='Нутриенты')),
                ('purpose', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='purpose', to='bodybuilding.purpose')),
            ],
        ),
    ]
