# Generated by Django 4.2.5 on 2023-10-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodybuilding', '0004_remove_exercise_muscles_muscle_exercises'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('nutrients', models.CharField(max_length=50, verbose_name='Макронутриенты')),
                ('ingredients', models.TextField(blank=True, verbose_name='Ингридиенты')),
                ('cooking', models.TextField(blank=True, verbose_name='Готовка')),
            ],
        ),
    ]
