# Generated by Django 4.2.5 on 2023-10-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodybuilding', '0005_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('about', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
    ]
