# Generated by Django 4.2.5 on 2023-10-04 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodybuilding', '0005_purpose_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='purpose',
        ),
        migrations.DeleteModel(
            name='Purpose',
        ),
    ]
