# Generated by Django 4.2.5 on 2023-10-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodybuilding', '0006_sportnutrition'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportnutrition',
            name='tierList',
            field=models.CharField(choices=[('S', 'Богоподобно'), ('A', 'Отлично'), ('B', 'Есть но'), ('C', 'Зачем')], default='S', max_length=1),
        ),
    ]
