# Generated by Django 4.2.5 on 2023-11-03 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bodybuilding', '0009_alter_exercise_slug_alter_muscle_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie', models.IntegerField(verbose_name='Калории')),
                ('protein', models.IntegerField(verbose_name='Белки')),
                ('fat', models.IntegerField(verbose_name='Жиры')),
                ('carbs', models.IntegerField(verbose_name='Углеводы')),
                ('date', models.DateField(verbose_name='Дата')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
