# Generated by Django 5.0.1 on 2024-01-26 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodybuilding', '0010_caloriecount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='Адресс электронной почты')),
                ('password', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='caloriecount',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='bodybuilding.myuser'),
        ),
    ]
